/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

//dia chi
#define RCC_BASEADDR			0x40021000U
#define RCC_APB2ENR_OFFSET		0x18U
#define RCC_APB2ENR				(RCC_BASEADDR + RCC_APB2ENR_OFFSET)

#define GPIOC_BASEADDR			0x40011000U
#define GPIOC_CRH_OFFSET		0x04
#define GPIOC_CRH_ADDR			(GPIOC_BASEADDR + GPIOC_CRH_OFFSET)

#define GPIOC_ODR_OFFSET		0x0C
#define GPIOC_ODR_ADDR			(GPIOC_BASEADDR + GPIOC_ODR_OFFSET)


#define GPIOB_BASEADDR			0x40010C00U
#define GPIOB_CRH_OFFSET		0x04
#define GPIOB_CRH_ADDR			(GPIOB_BASEADDR + GPIOB_CRH_OFFSET)

#define GPIOB_IDR_OFFSET		0x08
#define GPIOB_IDR_ADDR			(GPIOB_BASEADDR + GPIOB_IDR_OFFSET)


#define GPIOB_ODR_OFFSET		0x0C
#define GPIOB_ODR_ADDR			(GPIOB_BASEADDR + GPIOB_ODR_OFFSET)

//thu tu bit
#define IOPCEN					4
#define MODE13					20
#define CNF13					22
#define ODR13					13

#define IOPBEN   			    3
#define MODE14					24
#define CNF14					26
#define ODR14					14
#define IDR14					14


void delay() {
	for(uint32_t i = 0; i < 100000; i++) {
		;
	}
}



void Config_GPIOC(void){
	uint32_t *ptr = (uint32_t *)RCC_APB2ENR;
	*ptr |= (1 << IOPCEN);
	ptr = (uint32_t *)GPIOC_CRH_ADDR;
	*ptr |= (3 << MODE13); // PC13 là đầu ra tốc độ 10MHz va modee
	*ptr &= ~(3 << CNF13);
	ptr = (uint32_t *)GPIOC_ODR_ADDR;
}

void Config_GPIOB(void){
	uint32_t *ptr = (uint32_t *)RCC_APB2ENR;
	*ptr |= (1 << IOPBEN);
	ptr = (uint32_t *)GPIOB_CRH_ADDR;
	*ptr &= ~(3 << MODE14); // PC14 là đầu vao
	*ptr &= ~(3 << CNF14);
	*ptr |= (2 << CNF14);
	ptr = (uint32_t *)GPIOB_ODR_ADDR;
	*ptr |= (1 << ODR14);
}

int main(void) {
	Config_GPIOC();
	Config_GPIOB();

    int ledState = 0;
    uint32_t *ptr;
    while (1) {
        // Kiểm tra trạng thái nút bấm
//        if (!(GPIOA->IDR & GPIO_IDR_IDR0)) { // Nếu nút bấm được nhấn
//            // Đảm bảo nút đã được thả trước khi đảo trạng thái LED
//            while (!(GPIOA->IDR & GPIO_IDR_IDR0));
//
//            // Đảo trạng thái LED
//            ledState = 1 - ledState;
//
//            // Đặt trạng thái LED
//            if (ledState) {
//                GPIOC->BSRR |= GPIO_BSRR_BS13; // Bật LED
//            } else {
//                GPIOC->BSRR |= GPIO_BSRR_BR13; // Tắt LED
//            }
//        }
    	ptr = (uint32_t *)GPIOB_IDR_ADDR;
    	if(!((*ptr >> IDR14) & 0x1))
    	{
    		ptr = (uint32_t *)GPIOC_ODR_ADDR;
    		*ptr |= (1 << ODR13);
    	}
    	else{
    		ptr = (uint32_t *)GPIOC_ODR_ADDR;
    		*ptr &= ~(1 << ODR13);
    	}
    }
}
